language: node_js
node_js: stable
install:
- npm install
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "Songchao"
- git config --global user.email zhangsongchao0504@gmail.com
- sed -i'' "s~git@github.com:zsc0504/zsc0504.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/zsc0504/zsc0504.gihub.io.git~" _config.yml
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
branches:
  only:
  - blog
env:
  global:
  - GH_REF: github.com/zsc0504/zsc0504.github.io.git
  - secure: tXJL17ShKEVi8idumZpZR6z1mgifgXWIZge49mhz9P8EpVsd+axEbzBYyTRBrsY9fMXeWGEJrmAX+ZNNkzI1WMxpDNHDc+R95WOGVXW4HTbhonO/Hqe9mIgpZA1u7h3a0V+TxTIZXBk0GvEWUc1vfxkraJCF88zXcQU4/qNh/zNE7CowxKiAkAfuofz9w7XZl9ODYcZyjzxMszbpxjQw1y7u/ENVjMaEEJMzFVwClSApVj6QRzduNbMCerKtioAahQFPbg1Yf2UERwdUJPCNcjSBCH+0VgzvtKkgEJn+3dW1qPbCsg2npyPCE7TgDDHUmhnmqZ8ubXcV+FJ7fCgcPchqeBEzX4/g3eZ8ybs6MP8lIoix39YUeV8RnHPRj4ootwZCxZ9bg1GlNl2c0/Y7FxHtUpX24p/42AF/xJU6edB7D7twzzUab3io9CID7r6ku37X2WiEPtqde+sl4ljUZcfTPIZX3DFHONtZWwsL/aByudz4LmO1Z2muy0HHQHBXRd/+nBsn+ZWnjsopxJEju2hB8BmG448c7QUM7dw30xKeqgIrly0XBQHBRRNBkvO/K09jupyQVk5/IqY22NLgBzFTIxko0YsKV/6NhhlkmuAjfqP4G90M7aa3KNfbqgyxwp6KTJGrNHttlIfosfGL2SvSS7yf6cqUg2twVr1gNOk=
